Linking library check is performed in configure.
Instead of showing `undefined reference to ...' during
the end of build (linking), performing library check is
more informative for finding out which library is missing.